#config_version=5

lights:
  l_laneA:
    number: 1-0-0
    subtype: led
    label:
    tags: white
  l_laneB:
    number: 1-0-1
    subtype: led
    label:
    tags: white
  l_laneC:
    number: 1-0-2
    subtype: led
    label:
    tags: white
  l_upper_bullseye:
    number: 1-0-3
    label:
    tags: white
  l_lower_bullseye:
    number: 1-0-4
    label:
    tags: white
  l_spinner:
    number: 1-0-5
    label:
    tags: white
  l_bonus10:
    number: 1-0-6
    label:
    tags: white
  l_multiplier2x:
    number: 1-0-10
    label:
    tags: white
  l_multiplier3x:
    number: 1-0-9
    label:
    tags: white
  l_multiplier4x:
    number: 1-0-8
    label:
    tags: white
  l_multiplier5x:
    number: 1-0-7
    label:
    tags: white
  l_shotagain:
    number: 1-0-11
    label:
    tags: white
  l_bonus1:
    number: 1-0-12
    subtype: led
    label:
    tags: white
  l_bonus2:
    number: 1-0-13
    subtype: led
    label:
    tags: white
  l_bonus3:
    number: 1-0-14
    label:
    tags: white
  l_bonus4:
    number: 1-0-15
    subtype: led
    label:
    tags: white
  l_bonus5:
    number: 1-0-16
    label:
    tags: white
  l_bonus6:
    number: 1-0-17
    label:
    tags: white
  l_bonus7:
    number: 1-0-18
    label:
    tags: white
  l_bonus8:
    number: 1-0-19
    label:
    tags: white
  l_bonus9:
    number: 1-0-20
    label:
    tags: white
  l_bonus20:
    number: 1-0-21
    label:
    tags: white
  l_drop1:
    number: 1-0-22
    label:
    tags: white
  l_drop3:
    number: 1-0-23
    label:
    tags: white
  l_drop5:
    number: 1-0-24
    label:
    tags: white
  l_extraball:
    number: 1-0-25
    label:
    tags: white
  l_lspecial:
    number: 1-0-26
    label:
    tags: white
  l_rspecial:
    number: 1-0-27
    label:
    tags: white
  l_10x1:
    number: 1-0-28
    label:
    tags: white
  l_10x2:
    number: 1-0-29
    label:
    tags: white
  l_10x3:
    number: 1-0-30
    label:
    tags: white
  l_hit1:
    number: 1-0-31
    label:
    tags: white
  l_hit2:
    number: 1-0-32
    label:
    tags: white
  l_hit3:
    number: 1-0-33
    label:
    tags: white




